scalaVersion := "2.13.12"
name := "playground"
organization := "ch.epfl.scala"
version := "1.0"
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "2.1.1"
libraryDependencies += "org.scodec" %% "scodec-core" % "1.11.9"